 # schema.yml

 version: 2

 sources:
   - name: raw
     schema: gz_raw_data
     tables:
       - name: product
         identifier: raw_gz_product
         description: Products of Greenweez 
  
         columns:
          - name: products_id
            description: identifier of each of Greeweez's product 
            tests:
               - unique
               - not_null              
          - name: purchase_price
            description: price of the purchase of each of Greeweez's products

       - name: sales
         identifier: raw_gz_sales
         description: Sales of Greenweez 

         # Freshness testing - make sure to fill in the ...
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         freshness:
           warn_after: 
              count : 1
              period: minute
              
         columns:
          - name: date_date
            description: date of purchase 
          - name: orders_id
            description: identifier of orders 
          - name: product_id
            description: identifier of products
          - name: revenue
            description: Total revenue of Greenweez's sales
          - name: quantity 
            description: The quantity of sales
       - name: ship
         identifier: raw_gz_ship
         description: Shipping of Greenweez 
         columns:
          - name: orders_id
            description: identifier of orders
            tests:
               - unique
               - not_null
          - name: shipping_fee
            description: the fee of the shipping services
          - name: logcost
            description: the cost of the logistic means
          - name: ship_cost
            description: the cost of the shipping services

       - name: adwords
         identifier : raw_gz_adwords
         description: adwords ads
         columns:
           - name: campaign_key
             description: primarykey
          
             tests :
             - unique
             - not_null
       - name: bing
         identifier : raw_gz_bing
         description: bing ads
         columns:
           - name: campaign_key
             description: primarykey
             tests :
             - unique
             - not_null
       - name: criteo
         identifier : raw_gz_criteo
         description: criteo ads
         columns:
           - name: campaign_key
             description: primarykey
             tests :
             - unique
             - not_null
       - name: facebook
         identifier : raw_gz_facebook
         description: facebook ads
         columns:
           - name: campaign_key
             description: primarykey
             tests :
             - unique
             - not_null
       - name: campaigns
         identifier : int_campaigns 
         description: campaigns that are imtegrated in our ads
         columns:
           - name: campaign_key
             description: primarykey
             tests :
             - unique
             - not_null
       - name: _day
         identifier : int_campaigns_day
         description: campaign's day that are imtegrated in our ads
         columns:
           - name: date_date
             description: primarykey
             tests :
             - unique
             - not_null
           - name: campaign_name
             description: primarykey
             tests :
             - unique
             - not_null
       
       
